#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

path=(
  ${ZDOTDIR:-$HOME}/bin
  $path
)

if [[ -f "${ZDOTDIR:-$HOME}/.zshrc_local" ]]; then
  source ${ZDOTDIR:-$HOME}/.zshrc_local
fi
